 prepare:
	pip install virtualenv
	virtualenv env
	.\env\Scripts\activate
 	pip install flask flask_sqlalchemy flask_login flask_bcrypt flask_wtf wtforms email_validator

alternetive:
	pip install -r requirements.txt

run:
	flask run

database_build:
	python
	from app import db
	db.create_all()
	exit()

check:
	sqlite3
	.tables
	.exit
